
#GET http://localhost:4004/odata/v4/product/printhelloworld(input='Hello')

#GET http://localhost:4004/rest/product/MyFunction(category=2)

#GET http://localhost:4004/odata/v4/productshop/Products


GET http://localhost:4004/odata/v4/productshop/Supplier
